---
  - name: Build gitlab image from ./image/Dockerfile
    become: true
    #command: "docker run --detach --hostname localhost --env 'GITLAB_PORT=10080' --env 'GITLAB_SSH_PORT=10022' --publish 10022:22 --publish 10080:80 --name gitlab --restart always --volume /srv/gitlab/config:/etc/gitlab --volume /srv/gitlab/logs:/var/log/gitlab --volume /srv/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce:latest"
    command: "docker build ./image -t gitlab"
    tags:
      - "gitlab_build"
      - "gitlab"

  - name: Run gitlab as docker container
    become: true
    command: "docker run --detach --name gitlab \
    --publish 10022:22 --publish 10080:80 \
    --hostname gitlab-container.vm \
    --volume /srv/gitlab/config:/etc/gitlab \
    --volume /srv/gitlab/logs:/var/log/gitlab \
    --volume /srv/gitlab/data:/var/opt/gitlab \
    gitlab"
    tags:
      - "gitlab_run"
      - "gitlab"

      #-detach
      #-P
      #--volume /srv/gitlab/config:/etc/gitlab
      #--volume /srv/gitlab/logs:/var/log/gitlab
      #--volume /srv/gitlab/data:/var/opt/gitlab
