---
- name: Create this VMs local gitlab directories
  file: path={{ item }} 
        state=directory 
        mode="u=rwx,g=rwx,o=rx"
  with_items: gitlab_directories

- name: Create this VMs local gitlab directories manually
  file: 
    path: "/srv/gitlab/logs"
    state: directory 
    mode: "u=rwx,g=rwx,o=rx"