---
- name: Download IntelliJ from release repository
  get_url: 
    url: "{{ repository_url }}{{ intelliJ_build_number }}/{{ filename }}{{ intelliJ_build_number }}{{ file_ext }}"
    dest: /tmp/intelliJ-{{ intelliJ_build_number }}{{ file_ext }}

- name: Create Installation Directory
  file: path=/opt/intelliJ-{{ intelliJ_build_number }} state=directory

- name: Move download to destination directory
  command: cp /tmp/intelliJ-{{ intelliJ_build_number }}{{ file_ext }} /opt/intelliJ-{{ intelliJ_build_number}}/release{{ file_ext }}

- name: Create directory to extract files
  file: path=/opt/intelliJ-{{ intelliJ_build_number }}/release state=directory

- name: Extract archive
  unarchive:
    src:  /opt/intelliJ-{{ intelliJ_build_number }}/release{{ file_ext }}
    dest: /opt/intelliJ-{{ intelliJ_build_number }}/release

- name: Delete archive
  file: path=/opt/intelliJ-{{ intelliJ_build_number }}/release{{ file_ext }} state=absent
