---
- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true

- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') | default(ansible_env.HOME+'/go', true) }}"
  when: not result|failed

- debug: msg=

- name: go get gogs
  shell: go get -u github.com/gogits/gogs
  environment:
    GOPATH: "{{ go_path }}"
  register: gogs
  when: not result|failed

- debug: var=gogs

- name: Grab klar source from github.com/optiopay/klar
  shell: "go get github.com/optiopay/klar"
  environment:
    GOPATH: "{{ go_path }}"
  tags:
    - "klar_build"

- name: Change to project Directory
  shell: "cd $GOPATH/src/github.com/optiopay/klar"
  tags:
    - "klar_build"

- name: Build klar from source
  shell: CGO_ENABLED=0 go build -a -installsuffix cgo .
  tags:
    - "klar_build"
    
- name: Build klar docker image
  become: true
  shell: docker build -t cgelias/klar .
  tags:
    - "klar_build"  
    - "klar_docker_build"  

- name: Build klar docker image
  become: true
  shell: docker push cgelias/klar
  tags:
    - "klar_docker_push"  

- name: Copy klar config
  copy:
    src: klarconfig.env
    dest: /tmp/klarconfig.env
  tags:
    - "klar_run"  

- name: Run klar as docker container
  become: true
  command: docker run --env-file=/tmp/klarconfig.env klar postgres:9.5.1
  tags:
    - "klar_run"  