---
- name: Grab klar source from github.com/optiopay/klar
  command: go get github.com/optiopay/klar
  tags:
    - "klar_build"

- name: Change to project Directory
  command: cd $GOPATH/src/github.com/optiopay/klar
  tags:
    - "klar_build"

- name: Build klar from source
  command: CGO_ENABLED=0 go build -a -installsuffix cgo .
  tags:
    - "klar_build"
    
- name: Build klar docker image
  become: true
  command: docker build -t cgelias/klar .
  tags:
    - "klar_build"  
    - "klar_docker_build"  

- name: Build klar docker image
  become: true
  command: docker push cgelias/klar
  tags:
    - "klar_docker_push"  

- name: Copy klar config
  copy:
    src: klarconfig.env
    dest: /tmp/klarconfig.env
  tags:
    - "klar_run"  

- name: Run klar as docker container
  become: true
  command: docker run --env-file=/tmp/klarconfig.env klar postgres:9.5.1
  tags:
    - "klar_run"  