---
- name: check go version
  command: go version
  register: result
  changed_when: no
  ignore_errors: true
  tags:
    - "klar_build"

- set_fact:
    go_path: "{{ lookup('env', 'GOPATH') }}"  #"/home/pnradmin/elias_test/go"
  tags:
    - "klar_build"

- set_fact:
    go_root: "{{ lookup('env', 'GOROOT') }}" #"/usr/local/go"
  tags:
    - "klar_build"

- debug:
    msg: "fact: {{ go_root }}"
    tags:
    - "klar_build"
- debug:
    msg: "fact: {{ go_path }}"
    tags:
    - "klar_build"

- name: Grab klar source from github.com/optiopay/klar
  shell: go get   github.com/optiopay/klar
  #shell: go get -u github.com/gogits/gogs
  environment:
    GOPATH: "{{ go_path }}"
    GOROOT: "{{ go_root }}"
  tags:
    - "klar_build"

# - name: Change to project Directory
#   shell: "cd $GOPATH/src/github.com/optiopay/klar"
#   environment:
#     GOPATH: "{{ go_path }}"
#   tags:
#     - "klar_build"

- name: Build klar from source
  command: bash -lc "cd {{ go_path }}/src/github.com/optiopay/klar && GOPATH={{ go_path }} CGO_ENABLED=0 go build -a -installsuffix cgo ."
  # CGO_ENABLED=0 go build -a -installsuffix cgo .
  environment:
    GOPATH: "{{ go_path }}"
    GOROOT: "{{ go_root }}"
  tags:
    - "klar_build"
    
- name: Build klar docker image
  become: true
  shell: docker build -t cgelias/klar .
  tags:
    - "klar_docker_build"  

- name: Build klar docker image
  become: true
  shell: docker push cgelias/klar
  tags:
    - "klar_docker_push"  

- name: Copy klar config
  copy:
    src: klarconfig.env
    dest: /tmp/klarconfig.env
  tags:
    - "klar_run"  

- name: Run klar as docker container
  become: true
  command: docker run --env-file=/tmp/klarconfig.env klar postgres:9.5.1
  tags:
    - "klar_run"  